name: Telegram Bot

on:
  workflow_dispatch:

concurrency:
  group: Telegram-Bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ADMIN_CHAT_ID:  ${{ secrets.ADMIN_CHAT_ID }}
          GH_PAT_TOKEN:   ${{ secrets.GH_PAT_TOKEN }}
          GH_REPO:        ${{ secrets.GH_REPO }}
          LAMIX_URL:      ${{ secrets.LAMIX_URL }}
        run: python bot.py
