name: Telegram Bot

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}
        run: python bot.py
